-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2131
--   at:        2018-04-22 10:54:19 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

SPOOL monlib_schema_output.txt;

SET ECHO ON;

DROP SEQUENCE author_no_seq;

DROP SEQUENCE bor_no_seq;

DROP SEQUENCE branch_code_seq;

DROP SEQUENCE man_id_seq;

DROP SEQUENCE publ_no_seq;

DROP SEQUENCE sub_no_seq;

DROP TABLE author_title CASCADE CONSTRAINTS;

DROP TABLE authors CASCADE CONSTRAINTS;

DROP TABLE borrowers CASCADE CONSTRAINTS;

DROP TABLE branches CASCADE CONSTRAINTS;

DROP TABLE copies CASCADE CONSTRAINTS;

DROP TABLE identifiers CASCADE CONSTRAINTS;

DROP TABLE loans CASCADE CONSTRAINTS;

DROP TABLE managers CASCADE CONSTRAINTS;

DROP TABLE publishers CASCADE CONSTRAINTS;

DROP TABLE reservations CASCADE CONSTRAINTS;

DROP TABLE subject_title CASCADE CONSTRAINTS;

DROP TABLE subjects CASCADE CONSTRAINTS;

DROP TABLE titles CASCADE CONSTRAINTS;

CREATE TABLE author_title (
    tit_call_no   CHAR(20) NOT NULL,
    auth_no       NUMBER(4) NOT NULL
);

COMMENT ON COLUMN author_title.tit_call_no IS
    'tit_call_no: Dewey decimal call no of title';

COMMENT ON COLUMN author_title.auth_no IS
    'auth_no: Author number';

ALTER TABLE author_title ADD CONSTRAINT author_title_pk PRIMARY KEY ( tit_call_no,
auth_no );

CREATE TABLE authors (
    auth_no     NUMBER(4) NOT NULL,
    auth_name   VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN authors.auth_no IS
    'auth_no: Author number';

COMMENT ON COLUMN authors.auth_name IS
    'auth_name: author name';

ALTER TABLE authors ADD CONSTRAINT authors_pk PRIMARY KEY ( auth_no );

CREATE TABLE borrowers (
    bor_no               NUMBER(10) NOT NULL,
    bor_last_name        VARCHAR2(15) NOT NULL,
    bor_first_name       VARCHAR2(15) NOT NULL,
    bor_initial          CHAR(1),
    bor_add_street       VARCHAR2(25) NOT NULL,
    bor_add_area         VARCHAR2(15) NOT NULL,
    bor_add_state        VARCHAR2(3) NOT NULL,
    bor_add_postcode     CHAR(4) NOT NULL,
    bor_classification   VARCHAR2(12) NOT NULL,
    bor_special_status   CHAR(1) NOT NULL,
    bor_home_branch      NUMBER(3) NOT NULL
);

ALTER TABLE borrowers
    ADD CONSTRAINT bor_add_states_chk CHECK ( bor_add_state IN (
        'ACT',
        'JBT',
        'NSW',
        'NT',
        'QLD',
        'SA',
        'TAS',
        'VIC',
        'WA'
    ) );

ALTER TABLE borrowers
    ADD CONSTRAINT borrower_classification_domain CHECK ( bor_classification IN (
        'Adult',
        'Junior',
        'Organization'
    ) );

ALTER TABLE borrowers
    ADD CONSTRAINT bor_special_status_chk CHECK ( bor_special_status IN (
        'N',
        'Y'
    ) );

COMMENT ON COLUMN borrowers.bor_no IS
    'bor_no: Borrower Numeric ID';

COMMENT ON COLUMN borrowers.bor_last_name IS
    'bor_last_name: Last name of the borrower';

COMMENT ON COLUMN borrowers.bor_first_name IS
    'bor_first_name: First name of the borrower';

COMMENT ON COLUMN borrowers.bor_initial IS
    'bor_initial: Borrower Initial';

COMMENT ON COLUMN borrowers.bor_add_street IS
    'bor_add_street: Borrower''s address street name';

COMMENT ON COLUMN borrowers.bor_add_area IS
    'bor_add_area: Borrower''s address area';

COMMENT ON COLUMN borrowers.bor_add_state IS
    'bor_add_state: Borrower''s address state';

COMMENT ON COLUMN borrowers.bor_add_postcode IS
    'bor_add_postcode: Borrower''s post code';

COMMENT ON COLUMN borrowers.bor_classification IS
    'bor_classification: Borrower''s classification (Junior, Adult or Organization)';

COMMENT ON COLUMN borrowers.bor_special_status IS
    'bor_special_status: Special borrower''s status flag (Y/N)  for unpaid fine / reached loan limit / hold overdue books';

COMMENT ON COLUMN borrowers.bor_home_branch IS
    'branch_code: branch code';

ALTER TABLE borrowers ADD CONSTRAINT borrowers_pk PRIMARY KEY ( bor_no );

CREATE TABLE branches (
    branch_code           NUMBER(3) NOT NULL,
    branch_name           VARCHAR2(25) NOT NULL,
    branch_add_street     VARCHAR2(25) NOT NULL,
    branch_add_area       VARCHAR2(15) NOT NULL,
    branch_add_state      VARCHAR2(3) NOT NULL,
    branch_add_postcode   CHAR(4) NOT NULL,
    branch_phone_no       NUMBER(10) NOT NULL,
    man_id                NUMBER(3) NOT NULL
);

ALTER TABLE branches
    ADD CONSTRAINT branch_address_state_chk CHECK ( branch_add_state IN (
        'ACT',
        'JBT',
        'NSW',
        'NT',
        'QLD',
        'SA',
        'TAS',
        'VIC',
        'WA'
    ) );

COMMENT ON COLUMN branches.branch_code IS
    'branch_code: branch code';

COMMENT ON COLUMN branches.branch_name IS
    'branch_name: branch name';

COMMENT ON COLUMN branches.branch_add_street IS
    'branch_add_street: branch address street';

COMMENT ON COLUMN branches.branch_add_area IS
    'branch_add_area: branch address area';

COMMENT ON COLUMN branches.branch_add_state IS
    'branch_add_state: branch address state';

COMMENT ON COLUMN branches.branch_add_postcode IS
    'branch_add_postcode: branch address postcode';

COMMENT ON COLUMN branches.branch_phone_no IS
    'branch_phone_no: branch phone no';

COMMENT ON COLUMN branches.man_id IS
    'man_id: Manager ID Number';

ALTER TABLE branches ADD CONSTRAINT branches_pk PRIMARY KEY ( branch_code );

CREATE TABLE copies (
    cop_barcode_no     NUMBER(20) NOT NULL,
    cop_ctr_rsv_flag   CHAR(1) NOT NULL,
    cop_status         VARCHAR2(25) NOT NULL,
    tit_call_no        CHAR(20) NOT NULL,
    branch_code        NUMBER(3) NOT NULL
);

ALTER TABLE copies
    ADD CONSTRAINT cop_ctr_rsv_flag CHECK ( cop_ctr_rsv_flag IN (
        'N',
        'Y'
    ) );

COMMENT ON COLUMN copies.cop_barcode_no IS
    'cop_barcode_no: Unique barcode to identify copies of books';

COMMENT ON COLUMN copies.cop_ctr_rsv_flag IS
    'copies_ctr_rsv_flag: Counter reserve flag for the copies';

COMMENT ON COLUMN copies.cop_status IS
    'cop_status: Status of the copy (Available, On Loan, Reserved, etc.)';

COMMENT ON COLUMN copies.tit_call_no IS
    'tit_call_no: Dewey decimal call no of title';

COMMENT ON COLUMN copies.branch_code IS
    'branch_code: branch code';

ALTER TABLE copies ADD CONSTRAINT copies_pk PRIMARY KEY ( cop_barcode_no );

CREATE TABLE identifiers (
    ide_isbn      VARCHAR2(30) NOT NULL,
    tit_call_no   CHAR(20) NOT NULL
);

COMMENT ON COLUMN identifiers.ide_isbn IS
    'ide_isbn: ISBN Identifier';

COMMENT ON COLUMN identifiers.tit_call_no IS
    'tit_call_no: Dewey decimal call no of title';

ALTER TABLE identifiers ADD CONSTRAINT identifiers_pk PRIMARY KEY ( ide_isbn,
tit_call_no );

CREATE TABLE loans (
    loan_date                 DATE NOT NULL,
    loan_due_date             DATE NOT NULL,
    loan_status               VARCHAR2(8) NOT NULL,
    loan_actual_return_date   DATE,
    loan_fine_amount          NUMBER(7,2),
    loan_fine_payment_date    DATE,
    bor_no                    NUMBER(10) NOT NULL,
    cop_barcode_no            NUMBER(20) NOT NULL
);

ALTER TABLE loans
    ADD CONSTRAINT loan_status_chk CHECK ( loan_status IN (
        'ON LOAN',
        'RETURNED'
    ) );

COMMENT ON COLUMN loans.loan_date IS
    'loan_date: Date of the loan';

COMMENT ON COLUMN loans.loan_due_date IS
    'loan_due_date: Due date of the loan based on borrower''s classification';

COMMENT ON COLUMN loans.loan_status IS
    'loan_status: Status of the loan (Returned, On Loan)';

COMMENT ON COLUMN loans.loan_actual_return_date IS
    'loan_actual_return_date: Actual return date of the loan';

COMMENT ON COLUMN loans.loan_fine_amount IS
    'loan_fine_amount: Fine amount of loan (if applicable)';

COMMENT ON COLUMN loans.loan_fine_payment_date IS
    'loan_fine_payment_date: Fine payment date (if applicable)';

COMMENT ON COLUMN loans.bor_no IS
    'bor_no: Borrower Numeric ID';

COMMENT ON COLUMN loans.cop_barcode_no IS
    'cop_barcode_no: Unique barcode to identify copies of books';

ALTER TABLE loans ADD CONSTRAINT loans_ck_1 CHECK ( loan_due_date >= loan_date );

ALTER TABLE loans
    ADD CONSTRAINT loans_pk PRIMARY KEY ( loan_date,
    bor_no,
    cop_barcode_no );

CREATE TABLE managers (
    man_id            NUMBER(3) NOT NULL,
    man_last_name     VARCHAR2(15) NOT NULL,
    man_first_name    VARCHAR2(15) NOT NULL,
    man_initial       CHAR(1),
    man_phone_no      NUMBER(10) NOT NULL,
    man_home_branch   NUMBER(3) NOT NULL
);

COMMENT ON COLUMN managers.man_id IS
    'man_id: Manager ID Number';

COMMENT ON COLUMN managers.man_last_name IS
    'manager_last_name: Last name of the manager';

COMMENT ON COLUMN managers.man_first_name IS
    'man_first_name: First name of manager';

COMMENT ON COLUMN managers.man_initial IS
    'man_initial: Manager''s Initial';

COMMENT ON COLUMN managers.man_phone_no IS
    'man_phone_no: Phone number of manager';

COMMENT ON COLUMN managers.man_home_branch IS
    'branch_code: branch code';

ALTER TABLE managers ADD CONSTRAINT managers_pk PRIMARY KEY ( man_id );

CREATE TABLE publishers (
    publ_no     NUMBER(4) NOT NULL,
    publ_name   VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN publishers.publ_no IS
    'publ_no: publisher number';

COMMENT ON COLUMN publishers.publ_name IS
    'publ_name: publisher name';

ALTER TABLE publishers ADD CONSTRAINT publishers_pk PRIMARY KEY ( publ_no );

CREATE TABLE reservations (
    res_date         DATE NOT NULL,
    bor_no           NUMBER(10) NOT NULL,
    cop_barcode_no   NUMBER(20) NOT NULL
);

COMMENT ON COLUMN reservations.res_date IS
    'res_date: timestamp of reservation for a copy';

COMMENT ON COLUMN reservations.bor_no IS
    'bor_no: Borrower Numeric ID';

COMMENT ON COLUMN reservations.cop_barcode_no IS
    'cop_barcode_no: Unique barcode to identify copies of books';

ALTER TABLE reservations
    ADD CONSTRAINT reservations_pk PRIMARY KEY ( res_date,
    bor_no,
    cop_barcode_no );

CREATE TABLE subject_title (
    tit_call_no   CHAR(20) NOT NULL,
    sub_no        NUMBER(4) NOT NULL
);

COMMENT ON COLUMN subject_title.tit_call_no IS
    'tit_call_no: Dewey decimal call no of title';

COMMENT ON COLUMN subject_title.sub_no IS
    'sub_no: subject number';

ALTER TABLE subject_title ADD CONSTRAINT subject_title_pk PRIMARY KEY ( tit_call_no,
sub_no );

CREATE TABLE subjects (
    sub_no     NUMBER(4) NOT NULL,
    sub_name   VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN subjects.sub_no IS
    'sub_no: subject number';

COMMENT ON COLUMN subjects.sub_name IS
    'sub_name: subject name';

ALTER TABLE subjects ADD CONSTRAINT subjects_pk PRIMARY KEY ( sub_no );

CREATE TABLE titles (
    tit_call_no           CHAR(20) NOT NULL,
    tit_title             VARCHAR2(30) NOT NULL,
    tit_description       VARCHAR2(1000) NOT NULL,
    tit_language          VARCHAR2(15) NOT NULL,
    tit_date_published    DATE NOT NULL,
    tit_edition           VARCHAR2(15) NOT NULL,
    tit_notes             VARCHAR2(50) NOT NULL,
    tit_no_of_pages       NUMBER NOT NULL,
    tit_purchcase_price   NUMBER(7,2) NOT NULL,
    tit_classification    VARCHAR2(9) NOT NULL,
    tit_read_lvl          NUMBER(2),
    publ_no               NUMBER(4) NOT NULL
);

ALTER TABLE titles
    ADD CONSTRAINT tit_classification_chk CHECK ( tit_classification IN (
        'FICTION',
        'REFERENCE'
    ) );

ALTER TABLE titles
    ADD CONSTRAINT tit_read_lvl_chk CHECK ( tit_read_lvl BETWEEN 1 AND 30 );

COMMENT ON COLUMN titles.tit_call_no IS
    'tit_call_no: Dewey decimal call no of title';

COMMENT ON COLUMN titles.tit_title IS
    'tit_title: title of the book';

COMMENT ON COLUMN titles.tit_description IS
    'tit_description: description';

COMMENT ON COLUMN titles.tit_language IS
    'tit_language: language of the copy';

COMMENT ON COLUMN titles.tit_date_published IS
    'tit_date_published: publishing date of the book';

COMMENT ON COLUMN titles.tit_edition IS
    'tit_edition: edition of the book';

COMMENT ON COLUMN titles.tit_notes IS
    'tit_notes: notes';

COMMENT ON COLUMN titles.tit_no_of_pages IS
    'tit_no_of_pages: no of pages';

COMMENT ON COLUMN titles.tit_purchcase_price IS
    'tit_purchasing_price: purchasing price of the book';

COMMENT ON COLUMN titles.tit_classification IS
    'tit_classification: Classification (Reference / Fiction)';

COMMENT ON COLUMN titles.tit_read_lvl IS
    'tit_read_lvl: Reading Level for fiction books (1-Easy to 30-Very Difficult)';

COMMENT ON COLUMN titles.publ_no IS
    'publ_no: publisher number';

ALTER TABLE titles ADD CONSTRAINT titles_pk PRIMARY KEY ( tit_call_no );

ALTER TABLE author_title
    ADD CONSTRAINT author_title_authors_fk FOREIGN KEY ( auth_no )
        REFERENCES authors ( auth_no );

ALTER TABLE author_title
    ADD CONSTRAINT author_title_titles_fk FOREIGN KEY ( tit_call_no )
        REFERENCES titles ( tit_call_no );

ALTER TABLE borrowers
    ADD CONSTRAINT borrowers_branches_fk FOREIGN KEY ( bor_home_branch )
        REFERENCES branches ( branch_code );

ALTER TABLE branches
    ADD CONSTRAINT branches_managers_fk FOREIGN KEY ( man_id )
        REFERENCES managers ( man_id );

ALTER TABLE copies
    ADD CONSTRAINT copies_branches_fk FOREIGN KEY ( branch_code )
        REFERENCES branches ( branch_code );

ALTER TABLE copies
    ADD CONSTRAINT copies_titles_fk FOREIGN KEY ( tit_call_no )
        REFERENCES titles ( tit_call_no );

ALTER TABLE identifiers
    ADD CONSTRAINT identifiers_titles_fk FOREIGN KEY ( tit_call_no )
        REFERENCES titles ( tit_call_no );

ALTER TABLE loans
    ADD CONSTRAINT loans_borrowers_fk FOREIGN KEY ( bor_no )
        REFERENCES borrowers ( bor_no );

ALTER TABLE loans
    ADD CONSTRAINT loans_copies_fk FOREIGN KEY ( cop_barcode_no )
        REFERENCES copies ( cop_barcode_no );

ALTER TABLE managers
    ADD CONSTRAINT managers_branches_fk FOREIGN KEY ( man_home_branch )
        REFERENCES branches ( branch_code );

ALTER TABLE reservations
    ADD CONSTRAINT reservations_borrowers_fk FOREIGN KEY ( bor_no )
        REFERENCES borrowers ( bor_no );

ALTER TABLE reservations
    ADD CONSTRAINT reservations_copies_fk FOREIGN KEY ( cop_barcode_no )
        REFERENCES copies ( cop_barcode_no );

ALTER TABLE subject_title
    ADD CONSTRAINT subject_title_subjects_fk FOREIGN KEY ( sub_no )
        REFERENCES subjects ( sub_no );

ALTER TABLE subject_title
    ADD CONSTRAINT subject_title_titles_fk FOREIGN KEY ( tit_call_no )
        REFERENCES titles ( tit_call_no );

ALTER TABLE titles
    ADD CONSTRAINT titles_publishers_fk FOREIGN KEY ( publ_no )
        REFERENCES publishers ( publ_no );

CREATE SEQUENCE author_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE bor_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE branch_code_seq START WITH 100 NOCACHE ORDER;

CREATE SEQUENCE man_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE publ_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE sub_no_seq START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             37
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF;

SET ECHO OFF;
-- END --